//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Jobnumber { get; set; }
        public string Name { get; set; }
        public string Passwords { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string RoleId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
