//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchupDetail
    {
        public int Id { get; set; }
        public int MatchupId { get; set; }
        public int Quarter { get; set; }
        public int Team_Away_Score { get; set; }
        public int Team_Home_Score { get; set; }
    
        public virtual Matchup Matchup { get; set; }
    }
}
