//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchupLog
    {
        public int Id { get; set; }
        public int MatchupId { get; set; }
        public int Quarter { get; set; }
        public string OccurTime { get; set; }
        public int TeamId { get; set; }
        public int PlayerId { get; set; }
        public int ActionTypeId { get; set; }
        public string Remark { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Matchup Matchup { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
