//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nba
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostSeason
    {
        public int TeamId { get; set; }
        public int SeasonId { get; set; }
        public int Rank { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
    }
}
